### ISSUE TITLE
Convert termui to vendor

### ISSUE THREAD

**Issue by mook-as** [hpcloud/termui#5]
Need to convert this repo to use Go 1.6 style vendoring, instead of Godep.
(Whether we stick with Godep or go with something else doesn't matter, but it currently doesn't like to build tests and things with Go 1.6)

**Comment by aarondl** [comment]
We won't actually vendor libraries because it's not good practice.

This issue came up because running the tests in the library is annoying without having the things vendored, but the presence of the Godep file should allow us to restore the versions that were there if we need to run the tests.
